- src/main/java/si/banka/korisnicki_servis/BankaApplication.java
- src/main/java/si/banka/korisnicki_servis/controller/UserController.java
- src/main/java/si/banka/korisnicki_servis/controller/response_forms/CreateUserForm.java
- src/main/java/si/banka/korisnicki_servis/filter/CustomAuthenticationFilter.java
- src/main/java/si/banka/korisnicki_servis/filter/CustomAuthorizationFilter.java
- src/main/java/si/banka/korisnicki_servis/model/Permissions.java
- src/main/java/si/banka/korisnicki_servis/model/User.java
- src/main/java/si/banka/korisnicki_servis/security/SecurityConfiguration.java
- src/main/java/si/banka/korisnicki_servis/service/UserService.java
- src/main/java/si/banka/korisnicki_servis/service/implementation/UserServiceImplementation.java
Create/delete user and password validation
> Added create/delete user

- src/main/java/si/banka/korisnicki_servis/filter/CustomAuthenticationFilter.java
- src/main/java/si/banka/korisnicki_servis/service/implementation/UserServiceImplementation.java
Oznaceno gde treba da se doda provera da li je user aktivan pri loginu, i pass validation pomeren sa logina na register
> [WIP] Manipulacija korisnika

- pom.xml
- src/main/java/si/banka/korisnicki_servis/config/SwaggerFoxConfig.java
- src/main/java/si/banka/korisnicki_servis/controller/UserController.java
- src/main/resources/application.properties
Dodata api dokumentacija koristeci swagger za CRUD operacije u korisnickom servisu. 
Treba dopuniti kada se zavrsi 2FA autentikacija.
> Dodata api dokumentacija (swagger) za korisnicke rute

- pom.xml
- src/main/java/si/banka/korisnicki_servis/BankaApplication.java
- src/main/java/si/banka/korisnicki_servis/controller/UserController.java
- src/main/java/si/banka/korisnicki_servis/controller/response_forms/OtpQRForm.java
- src/main/java/si/banka/korisnicki_servis/controller/response_forms/OtpToSecretForm.java
- src/main/java/si/banka/korisnicki_servis/controller/response_forms/OtpToUserForm.java
- src/main/java/si/banka/korisnicki_servis/filter/CustomAuthenticationFilter.java
- src/main/java/si/banka/korisnicki_servis/model/User.java
- src/main/java/si/banka/korisnicki_servis/security/OTPUtilities.java
- src/main/java/si/banka/korisnicki_servis/security/SecurityConfiguration.java
- src/main/java/si/banka/korisnicki_servis/security/otp/OTPCredentials.java
- src/main/java/si/banka/korisnicki_servis/security/otp/OtpAuthenticationManager.java
- src/main/java/si/banka/korisnicki_servis/security/otp/OtpAuthenticationToken.java
- src/main/java/si/banka/korisnicki_servis/service/UserService.java
- src/main/java/si/banka/korisnicki_servis/service/implementation/UserServiceImplementation.java
Work in progress
Closes #5
* Prvo se generise random kljuc pomocu generateSeecret  apija
* Pomocu tog ljuca se generise qr kod pomocu generateQrImage  apija
* Ako korisnik potvrdi qr kod onda se namesti kljuc pomocu setSeecret  apija
* Korisnik mora da ima TOTP kompatibilnu aplikaciju za 2FA (Google Authenticator, andOtp, TOTP Authenticator)
* Pomocu svoje aplikacije skenira qr kod.
* Pri svakom loginu korisnik mora da pogleda koj je njegov sestocifreni kljuc i da ga unese pri loginu
> Two Factor Authentication

- berza/src/main/java/si/banka/berza/controller/BerzaController.java
- berza/src/main/java/si/banka/berza/model/Akcije.java
- berza/src/main/java/si/banka/berza/model/Berza.java
- berza/src/main/java/si/banka/berza/model/Forex.java
- berza/src/main/java/si/banka/berza/model/FuturesUgovori.java
- berza/src/main/java/si/banka/berza/model/HartijaOdVrednosti.java
- berza/src/main/java/si/banka/berza/model/Valuta.java
- berza/src/main/java/si/banka/berza/service/BerzaService.java
Neki tipovi promenjivih mozda nisu skroz tacni, potrebno je razmotriti ih.
> Dodavanje modela, 

- .idea/.gitignore
- .idea/Banka-Back.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- berza/.gitignore
- berza/src/main/java/si/banka/berza/controller/FuturesUgovoriController.java
Added controller for FuturesUgovori
> Berza 1 pull request

- .github/workflows/build.yml
- berza/Dockerfile
- berza/src/main/resources/application.properties
- docker-compose.yml
- pom.xml
* Berza dodata u root `pom.xml`
* Berza dodata u `docker-compose.yml`
* Dodat `Dockerfile` za berzu
* Port berze promenjen na 8082
* Dodata nova PostgreSQL instance u `docker-compose.yml` koja radi na portu `5433`
* Dodat SonarCloud za berzu
> Integracija berze

- .github/workflows/influxscrapper-service.yml
> Add sonar influx coverage scanner

- .github/workflows/berza-service.yml
- .github/workflows/influxscrapper-service.yml
- .github/workflows/mail-service.yml
- .github/workflows/user-service.yml
Ovaj PR menja Actions workflow-ove tako da će se workflow-ovi pokrenuti ukoliko se promeni njihova definicija. Ovo pomaže u situacijama poput #175 gde se promenila samo definicija, pa se workflow nije pokrenuo.
> Pokreni Actions workflow-ove ako se promeni definicija

- berza/src/main/java/rs/edu/raf/banka/berza/service/impl/AkcijePodaciService.java
- berza/src/main/java/rs/edu/raf/banka/berza/service/impl/ForexPodaciService.java
- berza/src/main/java/rs/edu/raf/banka/berza/service/impl/FuturesUgovoriPodaciService.java
- berza/src/test/java/rs/edu/raf/banka/berza/AkcijeServiceTest.java
- berza/src/test/java/rs/edu/raf/banka/berza/BerzaServiceTest.java
- berza/src/test/java/rs/edu/raf/banka/berza/DateUtilsTest.java
- berza/src/test/java/rs/edu/raf/banka/berza/ForexPodaciServiceTest.java
- berza/src/test/java/rs/edu/raf/banka/berza/FuturesUgovoriPodaciServiceTest.java
- berza/src/test/java/rs/edu/raf/banka/berza/OrderServiceTest.java
- berza/src/test/java/rs/edu/raf/banka/berza/TransakcijaServiceTest.java
Sada i sa zadovoljavajucim coverage
> Dodati testovi za Service Impl

- README.md
- user-service/pom.xml
- user-service/src/main/java/rs/edu/raf/banka/user_service/BankaApplication.java
- user-service/src/main/java/rs/edu/raf/banka/user_service/controller/UserController.java
- user-service/src/main/java/rs/edu/raf/banka/user_service/controller/response_forms/ChangeLimitForm.java
- user-service/src/main/java/rs/edu/raf/banka/user_service/controller/response_forms/CreateUserForm.java
- user-service/src/main/java/rs/edu/raf/banka/user_service/cron/ResetLimitScheduler.java
- user-service/src/main/java/rs/edu/raf/banka/user_service/model/Permissions.java
- user-service/src/main/java/rs/edu/raf/banka/user_service/model/User.java
- user-service/src/main/java/rs/edu/raf/banka/user_service/security/SecurityConfiguration.java
- user-service/src/main/java/rs/edu/raf/banka/user_service/service/UserService.java
- user-service/src/main/java/rs/edu/raf/banka/user_service/service/implementation/UserServiceImplementation.java
Implementirao managovanje agenata. U inicijalizaciju baze dodao dva agenta i dva supervisora.
> Add actuators

- berza/pom.xml
- berza/src/main/java/rs/edu/raf/banka/berza/configuration/SwaggerFoxConfig.java
- racun-service/pom.xml
- racun-service/src/main/java/rs/edu/raf/banka/racun/config/SwaggerFoxConfig.java
- racun-service/src/main/resources/application.properties
Dodata swagger dokumentacija, za berzu radi, a za racun servis ne radi, mada mislim da je do dockera. Treba proveriti.
> dodata swagger dokumentacija u berzi i racun servisu

- berza/src/main/java/rs/edu/raf/banka/berza/controller/BerzaController.java
- berza/src/main/java/rs/edu/raf/banka/berza/repository/HartijaRepository.java
- berza/src/main/java/rs/edu/raf/banka/berza/service/impl/HartijaService.java
> Hartija near settlement api

- docker-compose.yml
- racun-service/src/main/java/rs/edu/raf/banka/racun/controller/RacunController.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/model/Transakcija.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/repository/TransakcijaRepository.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/requests/TransakcijaRequest.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/TransakcijaService.java
- racun-service/src/main/resources/application.properties
- user-service/src/main/java/rs/edu/raf/banka/user_service/controller/UserController.java
Promena limita ne radi, treba popraviti.
> rezervacija sredstava i promena limta

- InfluxScrapper/InfluxScrapper/Models/Constants.cs
- racun-service/src/main/java/rs/edu/raf/banka/racun/controller/RacunController.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/repository/TransakcijaRepository.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/TransakcijaService.java
> pregled transakcika-ispravke

- InfluxScrapper/InfluxScrapper/Models/Constants.cs
- docker-compose.yml
- racun-service/pom.xml
- racun-service/src/main/java/rs/edu/raf/banka/racun/config/SpringConfig.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/controller/RacunController.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/dto/AgentSredstvaKapitalDto.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/dto/SredstvaKapitalDto.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/dto/UserDto.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/repository/SredstvaKapitalRepository.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/SredstvaKapitalService.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/TransakcijaService.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/UserService.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/utils/HttpUtils.java
- racun-service/src/main/resources/application.properties
Supervizori vide celokupno stanje na racunu.
Agenti vide odredjene atribute.
> Milestone 4

- berza/src/main/java/rs/edu/raf/banka/berza/controller/BerzaController.java
- berza/src/main/java/rs/edu/raf/banka/berza/service/impl/HartijaService.java
- racun-service/pom.xml
- racun-service/src/main/java/rs/edu/raf/banka/racun/controller/RacunController.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/enums/KapitalType.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/model/ForexPodaciDto.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/model/KapitalStanje.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/model/SredstvaKapital.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/repository/SredstvaKapitalRepository.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/requests/TransakcijaRequest.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/SredstvaKapitalService.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/TransakcijaService.java
> Kapital sa hartijama

- user-service/src/main/java/rs/edu/raf/banka/user_service/BankaApplication.java
- user-service/src/main/java/rs/edu/raf/banka/user_service/mail/PasswordResetToken.java
- user-service/src/main/java/rs/edu/raf/banka/user_service/model/User.java
- user-service/src/main/java/rs/edu/raf/banka/user_service/service/implementation/UserServiceImplementation.java
- user-service/src/test/java/rs/edu/raf/banka/user_service/IntegrationTest.java
- user-service/src/test/java/rs/edu/raf/banka/user_service/UserServiceTest.java
* Prilikom kreiranja novog korisnika, korisniku se šalje email sa username-om i password-om
* Nakon uspešnog resetovanja lozinke, token se invalidira tako da ne može ponovo da se koristi. Slično, token se posle 5 minuta automatski invalidira ukoliko se ne iskoristi
* Email, username i JMBG polja u User entitetu su sada unique (duplikati nisu dozvoljeni)
> Popravljen UX za kreiranje novog naloga i resetovanje lozinke

- racun-service/src/main/java/rs/edu/raf/banka/racun/controller/CompanyController.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/exceptions/InvalidCompanyException.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/model/company/Company.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/model/company/CompanyBankAccount.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/model/company/CompanyContactPerson.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/repository/company/CompanyBankAccountRepository.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/repository/company/CompanyContactPersonRepository.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/repository/company/CompanyRepository.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/requests/CompanyBankAccountRequest.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/requests/CompanyContactPersonRequest.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/requests/CompanyRequest.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/CompanyBankAccountService.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/CompanyContactPersonService.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/CompanyService.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/utils/StringUtils.java
> Add Company entities, controller, repos, and services

- racun-service/src/main/java/rs/edu/raf/banka/racun/controller/UgovorController.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/model/contract/TransakcionaStavka.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/model/contract/Ugovor.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/repository/contract/UgovorRepository.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/requests/UgovorUpdateRequest.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/UgovorService.java
> Permisije za ugovore

- racun-service/src/main/java/rs/edu/raf/banka/racun/model/contract/TransakcionaStavka.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/UgovorService.java
> Merge transactions and ugovori

- racun-service/src/main/java/rs/edu/raf/banka/racun/controller/RacunController.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/requests/ValutaService.java
- racun-service/src/test/java/rs/edu/raf/banka/racun/RacunControllerTest.java
Dodata API ruta u račun servis da vrati listu svih valuta. Ruta je `http://localhost:8083/api/racun/valute`.
> Add an endpoint to list all currencies

- racun-service/src/main/java/rs/edu/raf/banka/racun/controller/UgovorController.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/enums/TransakcionaStavkaType.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/enums/UgovorStatus.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/exceptions/ContractExpcetion.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/UgovorService.java
API poziv je POST koji kao URL parametar uzima ID ugovora koji se odbija: `http://localhost:8083/api/ugovor/company/1`. Ovaj poziv nema body. Odbijanje ugovora automatski stornira sve rezervacije po transakcionim stavkama. Ugovor ne može da se odbije ukoliko je već finalizovan.
> Add API route for rejecting contracts

- berza/src/main/java/rs/edu/raf/banka/berza/controller/BerzaController.java
- berza/src/main/java/rs/edu/raf/banka/berza/requests/MarginTransakcijaRequest.java
- berza/src/main/java/rs/edu/raf/banka/berza/requests/MarginTransakcijaType.java
- berza/src/main/java/rs/edu/raf/banka/berza/response/MarginTransakcijaResponse.java
- berza/src/main/java/rs/edu/raf/banka/berza/service/impl/BerzaService.java
- berza/src/main/java/rs/edu/raf/banka/berza/service/impl/ForexPodaciService.java
- berza/src/main/java/rs/edu/raf/banka/berza/service/impl/FuturesUgovoriPodaciService.java
- berza/src/main/java/rs/edu/raf/banka/berza/service/impl/OrderService.java
- berza/src/main/java/rs/edu/raf/banka/berza/service/impl/PriceService.java
- berza/src/main/java/rs/edu/raf/banka/berza/service/remote/TransakcijaService.java
- berza/src/main/java/rs/edu/raf/banka/berza/utils/HttpUtils.java
- berza/src/test/java/rs/edu/raf/banka/berza/BerzaServiceTest.java
- berza/src/test/java/rs/edu/raf/banka/berza/OrderServiceTest.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/RacunApplication.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/bootstrap/BootstrapData.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/controller/MarginRacunController.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/enums/KapitalType.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/model/SredstvaKapital.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/model/margins/MarginTransakcija.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/repository/SredstvaKapitalRepository.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/requests/MarginTransakcijaRequest.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/response/AskBidPriceResponse.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/MarginTransakcijaService.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/RacunService.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/SredstvaKapitalService.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/utils/HttpUtils.java
Fixes #296 
Fixes #297 
Fixes #298 
Fixes #299 
Fixes #300 
Fixes #301
> Margin account and transactions implementation

- berza/src/main/java/rs/edu/raf/banka/berza/service/impl/OrderService.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/controller/MarginRacunController.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/controller/RacunController.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/dto/MarginTransakcijeHartijeDto.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/dto/SupervisorSredstvaKapitalDto.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/repository/MarginTransakcijaRepository.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/repository/TransakcijaRepository.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/MarginTransakcijaService.java
- racun-service/src/main/java/rs/edu/raf/banka/racun/service/impl/SredstvaKapitalService.java
- racun-service/src/test/java/rs/edu/raf/banka/racun/RacunControllerTest.java
- racun-service/src/test/java/rs/edu/raf/banka/racun/SredstvaKapitalaServiceTest.java
> Sredstva i kapital za marzne racune
